# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=100)),
                ('Long', models.FloatField()),
                ('Lat', models.FloatField()),
                ('ImgLink', models.URLField()),
            ],
        ),
    ]
